#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : scowl
Version  : 2018.04.16
Release  : 1
URL      : https://sourceforge.net/projects/wordlist/files/SCOWL/2018.04.16/scowl-2018.04.16.tar.gz
Source0  : https://sourceforge.net/projects/wordlist/files/SCOWL/2018.04.16/scowl-2018.04.16.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : Public-Domain
Requires: scowl-data = %{version}-%{release}
Requires: scowl-license = %{version}-%{release}
Patch1: 0001-Fix-makefile.patch

%description
Spell Checking Oriented Word Lists (SCOWL)
Version 2018.04.16
Mon Apr 16 22:11:56 2018 -0400 [7bbe293]
by Kevin Atkinson (kevina@gnu.org)

%package data
Summary: data components for the scowl package.
Group: Data

%description data
data components for the scowl package.


%package license
Summary: license components for the scowl package.
Group: Default

%description license
license components for the scowl package.


%prep
%setup -q -n scowl-2018.04.16
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1556905057
export LDFLAGS="${LDFLAGS} -fno-lto"
make  %{?_smp_mflags}


%install
export SOURCE_DATE_EPOCH=1556905057
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/scowl
cp Copyright %{buildroot}/usr/share/package-licenses/scowl/Copyright
cp r/yawl/LICENSE %{buildroot}/usr/share/package-licenses/scowl/r_yawl_LICENSE
%make_install

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/share/dict/words

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/scowl/Copyright
/usr/share/package-licenses/scowl/r_yawl_LICENSE
